import "./globals.css";
import localFont from "next/font/local";
import Screens from "@/components/Screens";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const amatic = localFont({
  src: [
    {
      path: "../public/fonts/AmaticSC-Bold.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-amatic",
});

export default function RootLayout({ children, props }) {
  return (
    <html lang="en" className={`${amatic.variable}`}>
      <body className="min-w-screen min-h-screen flex-col justify-between">
        <Screens />
        {children}
        <Footer />
      </body>
    </html>
  );
}
